# Generated by Django 4.2.1 on 2023-05-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('vehicle_vin', models.CharField(max_length=17)),
                ('vehicle_make', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('rental_start_date', models.DateField()),
                ('rental_duration', models.FloatField()),
                ('rental_day_rate', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
