# Generated by Django 4.1.3 on 2023-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mullsys_motors', '0003_alter_rental_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_id',
            field=models.IntegerField(default=-1),
        ),
    ]
